version: '3.9'

services:
  traefik:
    image: traefik:v3.5
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.127.0.0.1.nip.io`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=80
    restart: unless-stopped

  backend:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`backend.127.0.0.1.nip.io`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=8090
      # Middleware to strip /api prefix before forwarding
      - traefik.http.routers.backend.middlewares=strip-api
      - traefik.http.middlewares.strip-api.stripPrefix.prefixes=/api
    restart: unless-stopped
    volumes:
      - pb_data:/app/pb_data

volumes:
  pb_data:
