version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --log.level=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.routers.frontend.entrypoints=web
    restart: unless-stopped

  backend:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.backend.loadbalancer.server.port=8090
      - traefik.http.routers.backend.entrypoints=web
    restart: unless-stopped
    volumes:
      - pb_data:/app/pb_data

volumes:
  pb_data:
